rabot-common --> rabot-utils

diff --git a/glon b/glon
--- a/glon
+++ b/glon
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. rabot-common
+. rabot-utils
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot-common" >&2
+  echo "$0: Error while sourcing rabot-utils" >&2
   exit 1
 fi
 
diff --git a/grp b/grp
--- a/grp
+++ b/grp
@@ -3,9 +3,9 @@
 # Based upon Jonathan Hartley's grep customization
 # http://stackoverflow.com/a/7646963
 
-. rabot-common
+. rabot-utils
 if [ "$?" -ne "0" ]; then
-  echo "$0: Error while sourcing rabot-common" >&2
+  echo "$0: Error while sourcing rabot-utils" >&2
   exit 1
 fi
 
